# no from statement

# let's create a folder to work from 
workdir /code

# copy over our requirements
copy ./requirements.txt /code/requirements.txt

# install the python deps
run pip install --no-cache-dir --upgrade -r /code/requirements.txt

# copy over our source folder
copy ./src/ /code/

# no CMD or ENTRYPOINT
